### ISSUE TITLE
 How can I get the embedding vector value column similar to your example data from the VSCode Day 2024 exhibition?

### ISSUE THREAD

**Issue by christ25442544** [pamelafox/rag-on-postgres#12]
According to this clip, https://www.youtube.com/watch?v=iCDfAC4f25w on your part.
![image](https://github.com/pamelafox/rag-on-postgres/assets/124753618/5d009507-4ca0-4433-9ebf-257ede217eee)

Did you use the Azure OpenAI embedding ada-002 model to embed the value of each row and store it at the end?

How can I obtain that?
Thanks!

**Comment by pamelafox** [comment]
Good question! I've actually migrated this repo over to a different org, where I've provided help with that:

https://github.com/Azure-Samples/rag-postgres-openai-python/

There's a script here that computes embeddings and updates rows:
https://github.com/Azure-Samples/rag-postgres-openai-python/blob/main/src/fastapi_app/update_embeddings.py

I'm not positive that it works since I haven't run it in a while, so please let me know if it doesn't work and I'll fix it up. (I think I may have also restructured things between the two repos, so you may need to adapt it if you're using it with this older version of the repo).
